# Generated by Django 3.2.3 on 2021-05-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('peg_ratio', models.FloatField(max_length=100)),
                ('dividend_yield', models.FloatField(max_length=100)),
                ('price_per_lpa', models.FloatField(max_length=100)),
                ('lpa', models.FloatField(max_length=100)),
                ('vpa', models.FloatField(max_length=100)),
                ('roe', models.FloatField(max_length=100)),
                ('cagr_profit', models.FloatField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
